In [3]:
import numpy as np

In [6]:
# first numpy array
first_numpy_array = np.array([1,2,3,4])

In [7]:
# printing our first array
print(first_numpy_array)

[1 2 3 4]


In [10]:
# array with only zeroes
array_with_zeros = np.zeros((3, 3))
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
# array with only ones
array_with_ones = np.ones((3, 3))
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array with empty values
array_with_empty = np.empty((2, 3))
print(array_with_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# array with arrange method
np_arange = np.arange(12)

In [19]:
# print array
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
# reshape method to change/create the array
np_arange.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# linspace method for linearly(equal) spaced data elements
np_linspace = np.linspace(0, 6, 4)      # np.linspace(first_element, last_element, total_number_of_equidistant_elements)
print(np_linspace)

[0. 2. 4. 6.]


In [26]:
# one-dimensional array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [27]:
# two-dimensional array
twoD_array = oneD_array.reshape(3, 5)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [47]:
# three-dimensional array
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [30]:
# ndim method of ndarray displays the no of dimensions of the array
print(oneD_array.ndim)
print(threeD_array.ndim)
print(twoD_array.ndim)

1
3
2


In [31]:
# shape method of ndarray

print(threeD_array.shape)
print(twoD_array.shape)
print(oneD_array.shape)

# output = (no_of_rows, no_of_cols, no_of_rank)

(3, 3, 3)
(3, 5)
(15,)


In [32]:
# size method of ndarray displays the no of elements in array

print(twoD_array.size)
print(oneD_array.size)
print(threeD_array.size)

15
15
27


In [43]:
# dtype method describes the type of elements in array

int_array = np.arange(10)
float_array = np.array(10, dtype="float")
string_array = np.array('n', dtype="|S5")

print(int_array)
print(int_array.dtype)
print(float_array.dtype)
print(string_array.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32
float64
|S5


# Basic oprations in NumPy

In [44]:
first_trial_cycle = [10, 15, 17, 26]
second_trial_cycle = [12, 11, 21, 24]

In [45]:
np_first_trial_cycle = np.array(first_trial_cycle)
np_second_trial_cycle = np.array(second_trial_cycle)

In [48]:
first_trial_cycle + first_trial_cycle  # adding the elements after first elements

[10, 15, 17, 26, 10, 15, 17, 26]

In [50]:
np_first_trial_cycle + np_first_trial_cycle   # addition of array elements of 2 arrays

array([20, 30, 34, 52])

In [51]:
np.add(45,10)

55

In [52]:
np.subtract(45,10)

35

### An example

In [53]:
np_daily_wage = np.array([7,9,13,8,11]) * 15
print(np_daily_wage)

[105 135 195 120 165]


In [54]:
sum(np_daily_wage)

720

### Comparison Operations

In [56]:
# create ndarray for weekly hours, 5 consecutive hours data
np_weekly_hours = np.array([23,41,55,47,38])

In [57]:
# week with more than 40 hours
np_weekly_hours[np_weekly_hours>40]

array([41, 55, 47])

In [58]:
# Week with more not equals to 40 hours
np_weekly_hours[np_weekly_hours!=40]

array([23, 41, 55, 47, 38])

### Logical operations

In [59]:
# Logical AND operation
np.logical_and(np_weekly_hours>20, np_weekly_hours<50)

array([ True,  True, False,  True,  True])

In [61]:
# Logical NOT operation
np.logical_not(np_weekly_hours>35)

array([ True, False, False, False, False])

In [64]:
# The corresponding rows:cols in ndarray is specified by below:

# (0,0) (0,1) (0,2) (0,3)
# (1,0) (1,1) (1,2) (1,3)

In [77]:
# Slicing array data where 1 is inclusive but 3 is not
# Use : to select all rows
# 1 -> starting index ,3 -> ending index-1

# np_trial_data_1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
# print(np_trial_data_1)

np_trial_data = np.zeros((3, 3))
trial_data = np_trial_data[:,1:3]
print(trial_data)
print("\n")

[[0. 0.]
 [0. 0.]
 [0. 0.]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
# print all elements using for loop
for i in np_trial_data:
    print(i)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]


### Indexing with Boolean arrays
### Conditional Arguments in ndarray

In [78]:
# Test scores of students in 4 different subjects 
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [80]:
# Passing score should be >60. So, given condition accordingly
pass_score = test_scores>60
print(pass_score)
# displays elements which fit criteria

[[ True  True False  True]
 [False  True  True False]]


In [82]:
# prints the elements which fit the criteria
test_scores[pass_score]

array([83, 71, 63, 68, 81])

### Universal functions

In [8]:
# sqrt
# cos
# sin
# floor
# exp

np_arr = np.sqrt([2,4,9,16])
print(np_arr)

[1.41421356 2.         3.         4.        ]


In [7]:
from numpy import pi
np.cos(0)

-1.0

In [11]:
np.sin(pi/2)

1.0

In [12]:
np.cos(pi)

-1.0

In [9]:
np.exp([0, 1, 5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [10]:
np.floor([1.3, 5.2, 3.7, -0.4, -10.0])

array([  1.,   5.,   3.,  -1., -10.])

In [13]:
# reshaping :
# 1. split
# 2. flatten
# 3. resize
# 4. reshape
# 5. stack

In [17]:
np_shape_manipulation = np.array([[23,1,54,34,76,23,67,40],[20,53,23,46,23,56,34,89]])
print(np_shape_manipulation)

[[23  1 54 34 76 23 67 40]
 [20 53 23 46 23 56 34 89]]


In [18]:
np_shape_manipulation.ravel()  # in single line

array([23,  1, 54, 34, 76, 23, 67, 40, 20, 53, 23, 46, 23, 56, 34, 89])

In [19]:
np_shape_manipulation.reshape(4,4)  # in array with rows,cols = 4,4

array([[23,  1, 54, 34],
       [76, 23, 67, 40],
       [20, 53, 23, 46],
       [23, 56, 34, 89]])

In [22]:
np_shape_manipulation.resize(8,2)  # 
print(np_shape_manipulation)

[[23  1]
 [54 34]
 [76 23]
 [67 40]
 [20 53]
 [23 46]
 [23 56]
 [34 89]]


In [24]:
np.hsplit(np_shape_manipulation, 2)   # splits the array into 2

[array([[23],
        [54],
        [76],
        [67],
        [20],
        [23],
        [23],
        [34]]),
 array([[ 1],
        [34],
        [23],
        [40],
        [53],
        [46],
        [56],
        [89]])]

In [31]:
np_arr_1 = np.array([12,45,8,23,56,34])
np_arr_2 = np.array([2,32,57,13,76,80])

In [32]:
np.hstack((np_arr_1, np_arr_2))

array([12, 45,  8, 23, 56, 34,  2, 32, 57, 13, 76, 80])

In [33]:
np_arr_1 * np_arr_2

array([  24, 1440,  456,  299, 4256, 2720])

In [35]:
var = 3.  # only if any one size is same or one of them has size is 1
np_arr_1 * var  # broadcasting multiplication in ndarray

array([ 36., 135.,  24.,  69., 168., 102.])

### transpose method

In [38]:
np_shape_manipulation

array([[23,  1],
       [54, 34],
       [76, 23],
       [67, 40],
       [20, 53],
       [23, 46],
       [23, 56],
       [34, 89]])

In [39]:
np_shape_manipulation.transpose()

array([[23, 54, 76, 67, 20, 23, 23, 34],
       [ 1, 34, 23, 40, 53, 46, 56, 89]])

In [42]:
np_inverse = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np_inverse)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
np.linalg.inv(threeD_array)   # only applied to square matrix
# np.linalg.inv(np_inverse)
# np.linalg.inv(array_with_ones)

LinAlgError: Singular matrix

In [44]:
np.trace(np_inverse)   # sum of one diagonal from left to right

15